version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install ruby-debug-ide --no-ri --no-rdoc
  - ps: Install-Product node '6.9.1'
  - npm install -g gulp
  - npm install
build_script:
  - npm run compile
test_script:
  - npm run test-debugger

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
